import os
from dotenv import load_dotenv

load_dotenv()

WASABI_ACCESS_KEY = os.getenv("WASABI_ACCESS_KEY")
WASABI_SECRET_KEY = os.getenv("WASABI_SECRET_KEY")
WASABI_ENDPOINT = os.getenv("WASABI_ENDPOINT")
WASABI_BUCKET_NAME = os.getenv("WASABI_BUCKET_NAME")
FIREWORK_API_KEY = os.getenv("FIREWORK_API_KEY")
REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN")
GEMINI_API_TOKEN = os.getenv("GEMINI_API_TOKEN")
ASSEMBLYAI_API_KEY = os.getenv("ASSEMBLYAI_API_KEY")
NEBIUS_API_KEY = os.getenv("NEBIUS_API_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
FRONTEND_URL = os.getenv("FRONTEND_URL")
IMAGE_PRICE = os.getenv("IMAGE_PRICE")
